application: cnpack-upgrade
version: 10
runtime: python
api_version: 1
skip_files: |
  (.*/.svn/.*)

default_expiration: "1h"

handlers:
- url: /cnwizards/latest/
  static_files: cnwizards/latest/index.html
  upload: cnwizards/latest/index.html

- url: /css
  static_dir: css

- url: /image
  static_dir: image

- url: /view/
  script: view.py

- url: /cnwizards/
  script: cwstat.py

- url: /tasks/.*
  script: cron.py

#- url: /geoip.py
#  script: geoip/geoip.py

- url: .*
  script: main.py
